Sprint2: burger-menu / slider / search
ClevertecFrontendLab/sprint2-tsakunova pull request #1
Opened 2023-02-06 11:33 UTC by tsakunova

2023-02-06 11:36 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675683365/slider%20one%20foto%20768px.png)

2023-02-06 11:48 UTC, klichkovskiy requested changes

2023-02-06 11:48 UTC, klichkovskiy commented on src/components/layout/components/header/header.tsx
> +          <MenuContainer onClick={burgerOpenHandler} onMouseOut={burgerOpenHandler}>
Сделай только по кликам. Никаких маусоут и тому подобного!

2023-02-06 11:48 UTC, klichkovskiy commented on src/components/layout/components/header/header.tsx
> +  const burgerOpenHandler = useCallback(() => {
Также высота контейнер с адаптивным меню должна быть меньше высоты экрана. У тебя меню уходит куда-то вниз.

2023-02-06 11:48 UTC, klichkovskiy commented on src/components/layout/layout.tsx
> +  const pathBook = useMatch(`/${RouteNames.books}/:category/:bookId`);
![image](https://user-images.githubusercontent.com/62481116/216963203-2e81e794-d451-4a04-9db7-e8700ec4047c.png)
Убери скролы со всего приложения!!!!

2023-02-06 11:48 UTC, klichkovskiy commented on src/components/navigation-menu/components/nav-list-item/nav-list-item.tsx
> +export const NavListItem: FC<NavListItemProps> = ({
По умолчанию меню с книгами скрыто на всех страницах, за исключением страниц с книгами

2023-02-06 19:26 UTC, tsakunova commented on src/components/navigation-menu/components/nav-list-item/nav-list-item.tsx
> +export const NavListItem: FC<NavListItemProps> = ({
Спасибо за комментарии, постаралась все исправить

2023-02-06 19:32 UTC, klichkovskiy requested changes

2023-02-06 19:32 UTC, klichkovskiy commented on src/components/navigation-menu/navigation-menu.tsx
> +  const renderMenu = useCallback(
![image](https://user-images.githubusercontent.com/62481116/217066273-fb0a913b-e078-438d-9756-c4e6770f3e90.png)
Эти две кнопки по умолчанию должны быть активны и иметь соответствующие стили

2023-02-06 19:32 UTC, klichkovskiy commented on src/components/navigation-menu/navigation-menu.tsx
> +  const renderMenu = useCallback(
При первом переходе на "Правила пользования" у "Витрины книг" пропадает стрелка
![image](https://user-images.githubusercontent.com/62481116/217066500-5ead2fa1-7c0b-4498-98c3-441d3c38e7c1.png)
При клике на "Витрину книг" происходит переход на страницу книг, но жанры не разворачиваются

2023-02-06 19:32 UTC, klichkovskiy commented on src/components/navigation-menu/navigation-menu.tsx
> +  const renderMenu = useCallback(
В идеале чтобы клик вне области адаптивного меню никуда не переходил. Сейчас если кликнуть при открытом адаптивном меню на книгу, то происходит переход на оную.

2023-02-07 19:22 UTC, tsakunova commented on src/components/navigation-menu/navigation-menu.tsx
> +  const renderMenu = useCallback(
Спасибо!
Добавлен оверлей, подсвечиваются активные роуты и дефолтные

2023-02-07 19:25 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1675797925/slider%20one%20foto%20768px.png)

2023-02-07 19:39 UTC, klichkovskiy approved these changes
Хорошая работа! Удачи на 3 спринте!

2023-02-07 19:43 UTC, merged